04_TagHelpers/Models/Employe.cs
using System.ComponentModel;

namespace _04_TagHelpers.Models
{
    public class Employe
    {
        public string Name { get; set; } = String.Empty;

        public double Salary { get; set; }

        [DisplayName("Actif")]
        public bool IsActif { get; set; }

        public string Email { get; set; } = String.Empty;

        public EmployeType Type { get; set; } = EmployeType.DEBUTANT;

        [DisplayName("Department")]
        public int DepartmentId { get; set; }
    }

    public enum EmployeType
    {
        DEBUTANT = 1,
        JUNIOR = 2,
        SENIOR = 3
    }
}

04_TagHelpers/Models/ErrorViewModel.cs
namespace _04_TagHelpers.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

04_TagHelpers/Controllers/EmployeController.cs
using _04_TagHelpers.Models;
using Microsoft.AspNetCore.Mvc;

namespace _04_TagHelpers.Controllers
{
    public class EmployeController : Controller
    {
        public IActionResult Create()
        {
            // return View(new Employe());
            return View("CreateHtmlHelper", new Employe());
        }

        public IActionResult Bonjour(Employe emp)
        {
            return View(emp);
        }
    }
}

04_TagHelpers/Views/Employe/Bonjour.cshtml
@using _04_TagHelpers.Helpers
@model Employe
@{
    ViewData["Title"] = "Bonjour Employe";
}

<h2> HTML TAGS </h2>
<a href="mailto:@Model.Email">@Model.Name</a> is @Model.Type and earn @Model.Salary

<h2> Custom Tag Helper </h2>

<!-- Utilisation d'un tag helper personnalisé défini dans le dossier Helpers ( ne pas oublier de rajouter le nom d'Assembly dans _ViewImports) -->
<employe name=@Model.Name salary=@Model.Salary type=@Model.Type email=@Model.Email />

<h2> Custom HTML Helper </h2>
<!-- Utilisation d'un html helper personnalisé défini dans le dossier Helpers -->
@Html.Employe(@Model.Name, @Model.Salary.ToString(), @Model.Type.ToString(), @Model.Email)

04_TagHelpers/Views/Employe/Create.cshtml
@model Employe
@{
    ViewData["Title"] = "Create Employe";
}

<h1> New Employe</h1>

<form method="post" asp-action="Bonjour"> 
    <div class="border p-3 mt-4">

        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
        </div>

        <div class="mb-3">
            <label asp-for="Salary"></label>
            <input asp-for="Salary" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="IsActif"></label>
            <input asp-for="IsActif" class="form-check-input" />
        </div>

        <div class="mb-3">
            <label asp-for="Type"></label>
            <select  asp-for="Type" class="form-control" asp-items="Html.GetEnumSelectList<EmployeType>()">
                <option>Please select one</option>
            </select>
        </div>

        <div class="mb-3">
            <label asp-for="DepartmentId"></label>
            <input asp-for="DepartmentId" class="form-control" />
        </div>

        <button tyep="submit" class="btn btn-primary" >Create</button>
    </div>
</form>

04_TagHelpers/Views/Employe/CreateHtmlHelper.cshtml
@model Employe
@{
    ViewData["Title"] = "Create Employe";
}

<h1> New Employe</h1>

@using (Html.BeginForm("Bonjour", "Employe", FormMethod.Post))
{
    <div class="border p-3 mt-4">
        <div class="mb-3">
            @Html.LabelFor(model => model.Name)
            @*@Html.TextBoxFor(model => model.Name, new { @class ="form-control"})*@
            @Html.EditorFor(model => model.Name, new {HtmlAttributes  = new { @class ="form-control"}})
        </div>
        <div class="mb-3">
            @Html.LabelFor(model => model.Salary)
            @Html.EditorFor(model => model.Salary, new {HtmlAttributes  = new { @class ="form-control"}})
        </div>
        <div class="mb-3">
            @Html.LabelFor(model => model.Email)
            @Html.EditorFor(model => model.Email, new {HtmlAttributes  = new { @class ="form-control"}})
        </div>
        <div class="mb-3">
            @Html.LabelFor(model => model.IsActif)
            @Html.EditorFor(model => model.IsActif, new {HtmlAttributes  = new { @class ="form-check-input"}})
        </div>
        <div class="mb-3">
            @Html.LabelFor(model => model.Type)
            @Html.DropDownListFor(model => model.Type, Html.GetEnumSelectList<EmployeType>(), "Select Type", new { @class ="form-control"})
        </div>
        <div class="mb-3">
            @Html.LabelFor(model => model.DepartmentId)
            @Html.EditorFor(model => model.DepartmentId, new {HtmlAttributes  = new { @class ="form-control"}})
        </div>
        <button tyep="submit" class="btn btn-primary">Create</button>
    </div>
}

04_TagHelpers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _04_TagHelpers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_04_TagHelpers.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Employe" asp-action="Bonjour">_04_TagHelpers</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _04_TagHelpers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>